name: sc4pac CI/CD

on:
  push:
    branches: [ "main", "action" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  channel:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel.yaml@main
    with:
      path: src/yaml
      channel-label: smf_16
      deploy-repository: sebamarynissen/sc4pac-channel
      use-stex-api: true
    secrets:
      stex-api-key: ${{ secrets.STEX_API_KEY }}
    permissions:
      pages: write
      id-token: write
